schema_version: 1
project:
  id: 90a1d66e-977a-4cd5-bfc4-3662a477be89
  name: "AEP Sample"
  git_url: "https://github.com/ritikadhandia/AEP-SAMPLE"
  default_branch: main
  created_by: "rdhandia@salesforce.com"
  created_at: 2026-06-18T06:14:44.975881+00:00
agentic:
  tool_version: "0.1.0"
  scaffolded_at: 2026-06-18T06:14:44.975881+00:00
